fix failed checkout

diff --git a/bin/git-myshellconfig-checkout b/bin/git-myshellconfig-checkout
--- a/bin/git-myshellconfig-checkout
+++ b/bin/git-myshellconfig-checkout
@@ -90,7 +90,8 @@ fi
 #echo $SGIT fetch ${MSC_GIT_REMOTE_NAME} -p 1>&2 
 if $dorepoupdate; then
     loginfo "fetch repo${dosubmodupdate:+ and submodules}"
-    $SGIT fetch ${dosubmodupdate:+--recurse-submodules} ${MSC_GIT_REMOTE_NAME} -p  2>>"${MSC_LOGFILE}"|| { logwarn fetch failed; gitupdateend; exit 1; }
+    #$SGIT fetch ${dosubmodupdate:+--recurse-submodules} ${MSC_GIT_REMOTE_NAME} -p  2>>"${MSC_LOGFILE}"|| { logwarn fetch failed; gitupdateend; exit 1; }
+    $SGIT fetch ${dosubmodupdate:+--recurse-submodules} ${MSC_GIT_BRANCH} -p  2>>"${MSC_LOGFILE}"|| { logwarn fetch failed; gitupdateend; exit 1; }
     if ${dosubmodupdate:-false}; then 
         lastupdatesubmodules
     fi
