add failuretrace

diff --git a/bashrc_add b/bashrc_add
--- a/bashrc_add
+++ b/bashrc_add
@@ -1,6 +1,14 @@
 #!/bin/bash
 #debug
 
+failure() {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg"
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
+
 # set SSHS to false, if not set
 if [ -z ${SSHS+x} ]; then export SSHS=false;fi
 
