remove failuretrap

diff --git a/bashrc_add b/bashrc_add
--- a/bashrc_add
+++ b/bashrc_add
@@ -1,12 +1,12 @@
 #!/bin/bash
 #debug
 
-failure() {
-  local lineno=$1
-  local msg=$2
-  echo "Failed at $lineno: $msg"
-}
-trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+#failure() {
+#  local lineno=$1
+#  local msg=$2
+#  echo "Failed at $lineno: $msg"
+#}
+#trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
 
 
 # set SSHS to false, if not set
